name: webdev_example_app
description: A web app example for webdev CLI.

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner: '>=1.3.0 <2.0.0'
  build_web_compilers: ^1.0.0

dependency_overrides:
  build_runner:
    path: /usr/local/google/home/grouma/Projects/build/build_runner
  build_runner_core:
    path: /usr/local/google/home/grouma/Projects/build/build_runner_core
  build_daemon:
    path: /usr/local/google/home/grouma/Projects/build/build_daemon
